name: Publish Docker Image

on:
  push:
    branches: [ release ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup enviroment
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"

      - name: Init project
        run: composer install --no-interaction --no-progress --ansi --no-dev --optimize-autoloader && php artisan vendor:publish --all && php artisan optimize

      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mrgeneralgoo/database-backup
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
